name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      matched: ${{ steps.filter.outputs.matched }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/path-filter@v4
        id: filter
        with:
          filters: |
            matched:
              - './fe/**'

  build:
    needs: check
    if: ${{ needs.check.outputs.matched == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
